/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedStudentRouteImport } from './routes/_authenticated/student'
import { Route as AuthenticatedProfilesRouteImport } from './routes/_authenticated/profiles'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedStudentIndexRouteImport } from './routes/_authenticated/student.index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedStudentRewardsRouteImport } from './routes/_authenticated/student.rewards'
import { Route as AuthenticatedStudentProgressRouteImport } from './routes/_authenticated/student.progress'
import { Route as AuthenticatedStudentAttendanceRouteImport } from './routes/_authenticated/student.attendance'
import { Route as AuthenticatedAdminAssignmentsRouteImport } from './routes/_authenticated/admin.assignments'
import { Route as AuthenticatedStudentSubjectSubjectIdRouteImport } from './routes/_authenticated/student.subject.$subjectId'
import { Route as AuthenticatedStudentLessonLessonIdRouteImport } from './routes/_authenticated/student.lesson.$lessonId'
import { Route as AuthenticatedStudentAssignmentAssignmentIdRouteImport } from './routes/_authenticated/student.assignment.$assignmentId'
import { Route as AuthenticatedAdminLessonLessonIdRouteImport } from './routes/_authenticated/admin.lesson.$lessonId'
import { Route as AuthenticatedAdminAssignmentAssignmentIdRouteImport } from './routes/_authenticated/admin.assignment.$assignmentId'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedStudentRoute = AuthenticatedStudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfilesRoute = AuthenticatedProfilesRouteImport.update({
  id: '/profiles',
  path: '/profiles',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStudentIndexRoute =
  AuthenticatedStudentIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedStudentRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedStudentRewardsRoute =
  AuthenticatedStudentRewardsRouteImport.update({
    id: '/rewards',
    path: '/rewards',
    getParentRoute: () => AuthenticatedStudentRoute,
  } as any)
const AuthenticatedStudentProgressRoute =
  AuthenticatedStudentProgressRouteImport.update({
    id: '/progress',
    path: '/progress',
    getParentRoute: () => AuthenticatedStudentRoute,
  } as any)
const AuthenticatedStudentAttendanceRoute =
  AuthenticatedStudentAttendanceRouteImport.update({
    id: '/attendance',
    path: '/attendance',
    getParentRoute: () => AuthenticatedStudentRoute,
  } as any)
const AuthenticatedAdminAssignmentsRoute =
  AuthenticatedAdminAssignmentsRouteImport.update({
    id: '/assignments',
    path: '/assignments',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedStudentSubjectSubjectIdRoute =
  AuthenticatedStudentSubjectSubjectIdRouteImport.update({
    id: '/subject/$subjectId',
    path: '/subject/$subjectId',
    getParentRoute: () => AuthenticatedStudentRoute,
  } as any)
const AuthenticatedStudentLessonLessonIdRoute =
  AuthenticatedStudentLessonLessonIdRouteImport.update({
    id: '/lesson/$lessonId',
    path: '/lesson/$lessonId',
    getParentRoute: () => AuthenticatedStudentRoute,
  } as any)
const AuthenticatedStudentAssignmentAssignmentIdRoute =
  AuthenticatedStudentAssignmentAssignmentIdRouteImport.update({
    id: '/assignment/$assignmentId',
    path: '/assignment/$assignmentId',
    getParentRoute: () => AuthenticatedStudentRoute,
  } as any)
const AuthenticatedAdminLessonLessonIdRoute =
  AuthenticatedAdminLessonLessonIdRouteImport.update({
    id: '/lesson/$lessonId',
    path: '/lesson/$lessonId',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAssignmentAssignmentIdRoute =
  AuthenticatedAdminAssignmentAssignmentIdRouteImport.update({
    id: '/assignment/$assignmentId',
    path: '/assignment/$assignmentId',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/profiles': typeof AuthenticatedProfilesRoute
  '/student': typeof AuthenticatedStudentRouteWithChildren
  '/admin/assignments': typeof AuthenticatedAdminAssignmentsRoute
  '/student/attendance': typeof AuthenticatedStudentAttendanceRoute
  '/student/progress': typeof AuthenticatedStudentProgressRoute
  '/student/rewards': typeof AuthenticatedStudentRewardsRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/student/': typeof AuthenticatedStudentIndexRoute
  '/admin/assignment/$assignmentId': typeof AuthenticatedAdminAssignmentAssignmentIdRoute
  '/admin/lesson/$lessonId': typeof AuthenticatedAdminLessonLessonIdRoute
  '/student/assignment/$assignmentId': typeof AuthenticatedStudentAssignmentAssignmentIdRoute
  '/student/lesson/$lessonId': typeof AuthenticatedStudentLessonLessonIdRoute
  '/student/subject/$subjectId': typeof AuthenticatedStudentSubjectSubjectIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/profiles': typeof AuthenticatedProfilesRoute
  '/admin/assignments': typeof AuthenticatedAdminAssignmentsRoute
  '/student/attendance': typeof AuthenticatedStudentAttendanceRoute
  '/student/progress': typeof AuthenticatedStudentProgressRoute
  '/student/rewards': typeof AuthenticatedStudentRewardsRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/student': typeof AuthenticatedStudentIndexRoute
  '/admin/assignment/$assignmentId': typeof AuthenticatedAdminAssignmentAssignmentIdRoute
  '/admin/lesson/$lessonId': typeof AuthenticatedAdminLessonLessonIdRoute
  '/student/assignment/$assignmentId': typeof AuthenticatedStudentAssignmentAssignmentIdRoute
  '/student/lesson/$lessonId': typeof AuthenticatedStudentLessonLessonIdRoute
  '/student/subject/$subjectId': typeof AuthenticatedStudentSubjectSubjectIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/profiles': typeof AuthenticatedProfilesRoute
  '/_authenticated/student': typeof AuthenticatedStudentRouteWithChildren
  '/_authenticated/admin/assignments': typeof AuthenticatedAdminAssignmentsRoute
  '/_authenticated/student/attendance': typeof AuthenticatedStudentAttendanceRoute
  '/_authenticated/student/progress': typeof AuthenticatedStudentProgressRoute
  '/_authenticated/student/rewards': typeof AuthenticatedStudentRewardsRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/student/': typeof AuthenticatedStudentIndexRoute
  '/_authenticated/admin/assignment/$assignmentId': typeof AuthenticatedAdminAssignmentAssignmentIdRoute
  '/_authenticated/admin/lesson/$lessonId': typeof AuthenticatedAdminLessonLessonIdRoute
  '/_authenticated/student/assignment/$assignmentId': typeof AuthenticatedStudentAssignmentAssignmentIdRoute
  '/_authenticated/student/lesson/$lessonId': typeof AuthenticatedStudentLessonLessonIdRoute
  '/_authenticated/student/subject/$subjectId': typeof AuthenticatedStudentSubjectSubjectIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/admin'
    | '/profiles'
    | '/student'
    | '/admin/assignments'
    | '/student/attendance'
    | '/student/progress'
    | '/student/rewards'
    | '/admin/'
    | '/student/'
    | '/admin/assignment/$assignmentId'
    | '/admin/lesson/$lessonId'
    | '/student/assignment/$assignmentId'
    | '/student/lesson/$lessonId'
    | '/student/subject/$subjectId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/profiles'
    | '/admin/assignments'
    | '/student/attendance'
    | '/student/progress'
    | '/student/rewards'
    | '/admin'
    | '/student'
    | '/admin/assignment/$assignmentId'
    | '/admin/lesson/$lessonId'
    | '/student/assignment/$assignmentId'
    | '/student/lesson/$lessonId'
    | '/student/subject/$subjectId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/sitemap.xml'
    | '/_authenticated/admin'
    | '/_authenticated/profiles'
    | '/_authenticated/student'
    | '/_authenticated/admin/assignments'
    | '/_authenticated/student/attendance'
    | '/_authenticated/student/progress'
    | '/_authenticated/student/rewards'
    | '/_authenticated/admin/'
    | '/_authenticated/student/'
    | '/_authenticated/admin/assignment/$assignmentId'
    | '/_authenticated/admin/lesson/$lessonId'
    | '/_authenticated/student/assignment/$assignmentId'
    | '/_authenticated/student/lesson/$lessonId'
    | '/_authenticated/student/subject/$subjectId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/student': {
      id: '/_authenticated/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof AuthenticatedStudentRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profiles': {
      id: '/_authenticated/profiles'
      path: '/profiles'
      fullPath: '/profiles'
      preLoaderRoute: typeof AuthenticatedProfilesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/student/': {
      id: '/_authenticated/student/'
      path: '/'
      fullPath: '/student/'
      preLoaderRoute: typeof AuthenticatedStudentIndexRouteImport
      parentRoute: typeof AuthenticatedStudentRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/student/rewards': {
      id: '/_authenticated/student/rewards'
      path: '/rewards'
      fullPath: '/student/rewards'
      preLoaderRoute: typeof AuthenticatedStudentRewardsRouteImport
      parentRoute: typeof AuthenticatedStudentRoute
    }
    '/_authenticated/student/progress': {
      id: '/_authenticated/student/progress'
      path: '/progress'
      fullPath: '/student/progress'
      preLoaderRoute: typeof AuthenticatedStudentProgressRouteImport
      parentRoute: typeof AuthenticatedStudentRoute
    }
    '/_authenticated/student/attendance': {
      id: '/_authenticated/student/attendance'
      path: '/attendance'
      fullPath: '/student/attendance'
      preLoaderRoute: typeof AuthenticatedStudentAttendanceRouteImport
      parentRoute: typeof AuthenticatedStudentRoute
    }
    '/_authenticated/admin/assignments': {
      id: '/_authenticated/admin/assignments'
      path: '/assignments'
      fullPath: '/admin/assignments'
      preLoaderRoute: typeof AuthenticatedAdminAssignmentsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/student/subject/$subjectId': {
      id: '/_authenticated/student/subject/$subjectId'
      path: '/subject/$subjectId'
      fullPath: '/student/subject/$subjectId'
      preLoaderRoute: typeof AuthenticatedStudentSubjectSubjectIdRouteImport
      parentRoute: typeof AuthenticatedStudentRoute
    }
    '/_authenticated/student/lesson/$lessonId': {
      id: '/_authenticated/student/lesson/$lessonId'
      path: '/lesson/$lessonId'
      fullPath: '/student/lesson/$lessonId'
      preLoaderRoute: typeof AuthenticatedStudentLessonLessonIdRouteImport
      parentRoute: typeof AuthenticatedStudentRoute
    }
    '/_authenticated/student/assignment/$assignmentId': {
      id: '/_authenticated/student/assignment/$assignmentId'
      path: '/assignment/$assignmentId'
      fullPath: '/student/assignment/$assignmentId'
      preLoaderRoute: typeof AuthenticatedStudentAssignmentAssignmentIdRouteImport
      parentRoute: typeof AuthenticatedStudentRoute
    }
    '/_authenticated/admin/lesson/$lessonId': {
      id: '/_authenticated/admin/lesson/$lessonId'
      path: '/lesson/$lessonId'
      fullPath: '/admin/lesson/$lessonId'
      preLoaderRoute: typeof AuthenticatedAdminLessonLessonIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/assignment/$assignmentId': {
      id: '/_authenticated/admin/assignment/$assignmentId'
      path: '/assignment/$assignmentId'
      fullPath: '/admin/assignment/$assignmentId'
      preLoaderRoute: typeof AuthenticatedAdminAssignmentAssignmentIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAssignmentsRoute: typeof AuthenticatedAdminAssignmentsRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminAssignmentAssignmentIdRoute: typeof AuthenticatedAdminAssignmentAssignmentIdRoute
  AuthenticatedAdminLessonLessonIdRoute: typeof AuthenticatedAdminLessonLessonIdRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAssignmentsRoute: AuthenticatedAdminAssignmentsRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminAssignmentAssignmentIdRoute:
    AuthenticatedAdminAssignmentAssignmentIdRoute,
  AuthenticatedAdminLessonLessonIdRoute: AuthenticatedAdminLessonLessonIdRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedStudentRouteChildren {
  AuthenticatedStudentAttendanceRoute: typeof AuthenticatedStudentAttendanceRoute
  AuthenticatedStudentProgressRoute: typeof AuthenticatedStudentProgressRoute
  AuthenticatedStudentRewardsRoute: typeof AuthenticatedStudentRewardsRoute
  AuthenticatedStudentIndexRoute: typeof AuthenticatedStudentIndexRoute
  AuthenticatedStudentAssignmentAssignmentIdRoute: typeof AuthenticatedStudentAssignmentAssignmentIdRoute
  AuthenticatedStudentLessonLessonIdRoute: typeof AuthenticatedStudentLessonLessonIdRoute
  AuthenticatedStudentSubjectSubjectIdRoute: typeof AuthenticatedStudentSubjectSubjectIdRoute
}

const AuthenticatedStudentRouteChildren: AuthenticatedStudentRouteChildren = {
  AuthenticatedStudentAttendanceRoute: AuthenticatedStudentAttendanceRoute,
  AuthenticatedStudentProgressRoute: AuthenticatedStudentProgressRoute,
  AuthenticatedStudentRewardsRoute: AuthenticatedStudentRewardsRoute,
  AuthenticatedStudentIndexRoute: AuthenticatedStudentIndexRoute,
  AuthenticatedStudentAssignmentAssignmentIdRoute:
    AuthenticatedStudentAssignmentAssignmentIdRoute,
  AuthenticatedStudentLessonLessonIdRoute:
    AuthenticatedStudentLessonLessonIdRoute,
  AuthenticatedStudentSubjectSubjectIdRoute:
    AuthenticatedStudentSubjectSubjectIdRoute,
}

const AuthenticatedStudentRouteWithChildren =
  AuthenticatedStudentRoute._addFileChildren(AuthenticatedStudentRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedProfilesRoute: typeof AuthenticatedProfilesRoute
  AuthenticatedStudentRoute: typeof AuthenticatedStudentRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedProfilesRoute: AuthenticatedProfilesRoute,
  AuthenticatedStudentRoute: AuthenticatedStudentRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
